# This workflow will sign an installer for the GenerateHCConfig4FLExTrans FLExTrans tool.

name: GenerateHCConfig4FLExTrans Sign and Release

on:
  push:
    paths:
      - 'Installer/Output/**'
      - '.github/workflows/generatehcconfig4flextrans-sign-release.yml'

jobs:
  preparation:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: GenerateHCConfig4FLExTrans
          path: GenerateHCConfig4FLExTrans/Installer/Output/GenerateHCConfigForFLExTrans.exe
          if-no-files-found: error

  sign-installer:
    name: Sign GenerateHCConfig4FLExTrans installer
    needs: preparation
    uses: sillsdev/codesign/.github/workflows/sign.yml@v2
    with:
      artifact: GenerateHCConfig4FLExTrans
    secrets:
      certificate: ${{ secrets.CODESIGN_LSDEVSECTIGOEV }}

  create-release:
    name: Create Release
    needs: sign-installer
    runs-on: windows-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: GenerateHCConfig4FLExTrans

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: GenerateHCConfigForFLExTransSetup.exe
          body: |
            Release for version ${{ github.ref }}
          draft: true
