# This workflow will sign an installer for the HCSynthByGloss FLExTrans tool.

name: HCSynthByGloss Sign and Release

on:
  push:
    paths:
      - 'HCSynthByGloss/Installer/Output/**'
      - '.github/workflows/hcsynthbygloss-sign-release.yml'

jobs:
  preparation:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: HCSynthByGloss
          path: HCSynthByGloss/Installer/Output/HCSynthByGlossSetup.exe
          if-no-files-found: error

  sign-installer:
    name: Sign HCSynthByGloss installer
    needs: preparation
    uses: sillsdev/codesign/.github/workflows/sign.yml@v2
    with:
      artifact: HCSynthByGloss
    secrets:
      certificate: ${{ secrets.CODESIGN_LSDEVSECTIGOEV }}

  create-release:
    name: Create Release
    needs: sign-installer
    runs-on: windows-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: HCSynthByGloss

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: HCSynthByGlossSetup.exe
          body: |
            Release for version ${{ github.ref }}
          draft: true
